
= Entwicklerhandbuch
Jürgen Zimmermann <Juergen.Zimmermann@HS-Karlsruhe.de>
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Im folgenden wird ein grober Überblick über den Applikationsserver gegeben. Es gibt die Rollen Admin, Mitarbeiter, Kunde und Premium-Kunde. Die jeweiligen Use-Cases für die verschiedenen Rollen sind hier zu sehen. Ein Admin kann einen Film suchen, einen Film anlegen, einen Film ändern und/oder löschen und Dateien hoch- und herunterladen. Ein Mitarbeiter kann einen Film suchen und Dateien hoch- und herunterladen. Ein Kunden kann einen Film anschauen und suchen. Ein Premium-Kunde kann Film suchen, anschauen und herunterladen.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

Die verschiedenen Komponenten des Applikationsservers: Ein RESTClient schickt einen Request ab und wird von der Router-Funktion entgegen genommen und an die Handler-Funktionen übergeben. Der Request wird dann an den Anwendungskern weitergeleitet. Der Anwendungskern kann z.B. einen Datenbank-Request ausführen oder eine Mail versenden (je nach Request). Zuletzt wird ein Response-Objekt gebaut und befüllt und an den RESTClient geschickt.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

Dies sind verschiedenen Handler-Funktionen, die an der REST-Schnittstelle ausgeführt werden können. Ein eingehender Request eines Clients wird über die Router-Funktion an die Handlerfunktionen weitergeleitet.

.Handler für die REST-Schnittstelle
[plantuml,FilmHandler,svg]
----
include::FilmHandler.puml[]
----

=== Der Anwendungskern

Der Anwendungskern beinhaltet die Service-Funktionen und die verschiedenen Entitäten. Man kann die Funktionen findById() und find() als Get-Methoden verstehen. Die create()-Funktion realisiert die Post-Methode. Update() kann man als Put-/Patch-Methode verstehen und delete() realisert die Delete-Methode. Somit werden im Anwendungskern die HTTP-Methoden durch die Service-Funktionen realisiert.

.Anwendungskern mit Mongoose
[plantuml,FilmService,svg]
----
include::FilmService.puml[]
----

=== Interface für Entities und das Mongoose-Model

Hier werden die Entities eines Filmes und deren Typ angezeigt. Ein Film hat dabei 2 Enum-Properties (Genre und Produktionsstudio). Die möglichen Werte eines Genres sind: Dokumentationen, Komödien und Dramen. Ein Produktionsstudio kann dabei die Werte: Disney, Universal, Warner Bros annehmen.

.Entity, Model und Schema
[plantuml,Film,svg]
----
include::Film.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
