// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

= Entwicklerhandfilm
Jürgen Zimmermann <Juergen.Zimmermann@HS-Karlsruhe.de>
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Im folgenden wird ein grober Überblick über den Applikationsserver gegeben. Ein Gast kann somit nur einen Film suchen und herunterladen, während ein Admin alle Use-Cases ausführen kann.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

Die verschiedenen Komponenten des Applikationsservers: Ein RESTClient schickt einen Request ab und wird von der Router-Funktion entgegen genommen und an die Handler-Funktionen übergeben. Der Request wird dann an den Anwendungskern weitergeleitet. Der Anwendungskern kann z.B. einen Datenbank-Request ausführen oder eine Mail versenden (je nach Request). Zuletzt wird ein Response-Objekt gebaut und befüllt und an den RESTClient geschickt.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

Dies sind verschiedenen Handler-Funktionen, die an der REST-Schnittstelle ausgeführt werden können.

.Handler für die REST-Schnittstelle
[plantuml,FilmHandler,svg]
----
include::FilmHandler.puml[]
----

=== Der Anwendungskern

Der Anwendungskern beinhaltet die Service-Funktionen und die verschiedenen Entitäten.

.Anwendungskern mit Mongoose
[plantuml,FilmService,svg]
----
include::FilmService.puml[]
----

=== Interface für Entities und das Mongoose-Model

Ein Film hat 2 Enum-Properties (Genre und Produktionsstudio).

.Entity, Model und Schema
[plantuml,Film,svg]
----
include::Film.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
