
@startuml Use Cases

left to right direction
skinparam packageStyle rect
skinparam componentStyle uml2

actor Kunde
actor PremiumKunde
actor Mitarbeiter
actor Admin

rectangle Streamingdienst {
    Kunde --> (Film suchen)
    Kunde --> (Film anschauen)
    PremiumKunde --> (Film anschauen)
    PremiumKunde --> (Film suchen)
    PremiumKunde --> (Film herunterladen)
    Mitarbeiter --> (Film suchen)
    Mitarbeiter --> (Datei hochladen)
    Mitarbeiter --> (Datei herunterladen)
    Admin --> (Film suchen)
    Admin --> (Film anlegen)
    Admin --> (Film ändern)
    Admin --> (Film löschen)
    Admin --> (Datei hochladen)
    Admin --> (Datei herunterladen)
}

footer (c) Enis Yesilbas

@enduml
